services:
  db:
    restart: unless-stopped
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: M450_db
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
        - -d
        - M450_db
        - -U
        - postgres
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: