name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./M450_LB1/gradlew

      - name: Run unit tests
        working-directory: ./M450_LB1
        run: ./gradlew test --info --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: |
            M450_LB1/build/test-results/test
            M450_LB1/build/reports/tests/test
